
GET http://localhost:3000/api/authors
###
POST http://localhost:3000/api/authors
Content-Type: application/json

{
    "name":"war book Creator",
    "town":"Vilnius",
    "bookId":"625e6f3f4c1517ac886454e3"
}
###

PATCH  http://localhost:3000/api/authors/625e57db63e69dff871dbb47
Content-Type: application/json

{
    "newName":"James bk1000"
}
###
PATCH  http://localhost:3000/api/authors/add-book/625e57db63e69dff871dbb47
Content-Type: application/json

{
    "bookId":"625e6f3f4c1517ac886454e3"
}
###

GET http://localhost:3000/api/books
###
GET http://localhost:3000/api/books/625e6f3f4c1517ac886454e3
###
DELETE  http://localhost:3000/api/books/625fb4ded94b2b01f115f66d
###
###
GET http://localhost:3000/api/books-agg2
###
GET http://localhost:3000/api/books-authors
###
POST http://localhost:3000/api/books
Content-Type: application/json

{
    "title":"war book 155",
    "year":2010,
    "rating":3
}
###

GET http://localhost:3000/api/categories
###